### ISSUE TITLE
Shortcut buttons/hotkeys for favourite languages?

### ISSUE THREAD

**Issue by gjcdeluxe** [chandler-stimson/speech-agent#1]
Hi, this is a super handy extension! Any chance of adding some assignable buttons or hotkeys to switch between multiple languages? It would be helpful for language learning sites like Duolingo, where it's constantly necessary to switch back and forth between languages.

**Comment by chandler-stimson** [comment]
Thanks for the report. Here is the list of language shortcuts for the 0.2.1 release

Open the interface: chrome://extensions/shortcuts
Close the interface: `Escape`
Select the next language: `Ctrl + K` or `Command + K`
Select the previous language: `Ctrl + J` or `Command + J`
Search for a language: `Ctrl + F` or `Command + F`

**Comment by gjcdeluxe** [comment]
Unfortunately Chrome's own internal shortcuts override Ctrl+J and Ctrl+K for me (Ctrl+J = Downloads, and Ctrl+K = Search)
